export const amToLat = (str: string): string => {
    switch (str) {
        case "ሀ":
        case "ሃ":
        case "ሐ":
        case "ሓ":
        case "ኀ":
        case "ኃ":
        case "ኻ":
            return "ha";
        case "ሁ":
        case "ሑ":
        case "ኁ":
        case "ኹ":
            return "hu";
        case "ሂ":
        case "ኂ":
        case "ሒ":
        case "ኺ":
            return "hi";
        case "ሄ":
        case "ሔ":
        case "ኄ":
        case "ኼ":
            return "hie";
        case "ህ":
        case "ሕ":
        case "ኅ":
        case "ኽ":
            return "h";
        case "ሆ":
        case "ሖ":
        case "ኆ":
        case "ኾ":
            return "ho";
        case "ኸ":
            return "he";
        case "ለ":
            return "le";
        case "ሉ":
            return "lu";
        case "ሊ":
            return "li";
        case "ላ":
            return "la";
        case "ሌ":
            return "lie";
        case "ል":
            return "l";
        case "ሎ":
            return "lo";
        case "ሏ":
            return "lwa";
        case "ዃ":
        case "ሗ":
        case "ኋ":
            return "hwa";
        case "መ":
            return "me";
        case "ሙ":
            return "mu";
        case "ሚ":
            return "mi";
        case "ማ":
            return "ma";
        case "ሜ":
            return "mie";
        case "ም":
            return "m";
        case "ሞ":
            return "mo";
        case "ሟ":
            return "mwa";
        case "ሠ":
        case "ሰ":
            return "se";
        case "ሡ":
        case "ሱ":
            return "su";
        case "ሢ":
        case "ሲ":
            return "si";
        case "ሣ":
        case "ሳ":
            return "sa";
        case "ሤ":
        case "ሴ":
            return "sie";
        case "ሥ":
        case "ስ":
            return "s";
        case "ሦ":
        case "ሶ":
            return "so";
        case "ሧ":
        case "ሷ":
            return "swa";
        case "ረ":
            return "re";
        case "ሩ":
            return "ru";
        case "ሪ":
            return "ri";
        case "ራ":
            return "ra";
        case "ሬ":
            return "rie";
        case "ር":
            return "r";
        case "ሮ":
            return "ro";
        case "ሯ":
            return "rwa";
        case "ሸ":
            return "śe";
        case "ሹ":
            return "śu";
        case "ሺ":
            return "śi";
        case "ሻ":
            return "śa";
        case "ሼ":
            return "śie";
        case "ሽ":
            return "ś";
        case "ሾ":
            return "śo";
        case "ሿ":
            return "śwa";
        case "ቀ":
            return "qe";
        case "ቁ":
            return "qu";
        case "ቂ":
            return "qi";
        case "ቃ":
            return "qa";
        case "ቄ":
            return "qie";
        case "ቅ":
            return "q";
        case "ቆ":
            return "qo";
        case "ቋ":
            return "qwa";
        case "በ":
            return "be";
        case "ቡ":
            return "bu";
        case "ቢ":
            return "bi";
        case "ባ":
            return "ba";
        case "ቤ":
            return "bie";
        case "ብ":
            return "b";
        case "ቦ":
            return "bo";
        case "ቧ":
            return "bwa";
        case "ቨ":
            return "ve";
        case "ቩ":
            return "vu";
        case "ቪ":
            return "vi";
        case "ቫ":
            return "va";
        case "ቬ":
            return "vie";
        case "ቭ":
            return "v";
        case "ቮ":
            return "vo";
        case "ቯ":
            return "vwa";
        case "ተ":
            return "te";
        case "ቱ":
            return "tu";
        case "ቲ":
            return "ti";
        case "ታ":
            return "ta";
        case "ቴ":
            return "tie";
        case "ት":
            return "t";
        case "ቶ":
            return "to";
        case "ቷ":
            return "twa";
        case "ቸ":
            return "će";
        case "ቹ":
            return "ću";
        case "ቺ":
            return "ći";
        case "ቻ":
            return "ća";
        case "ቼ":
            return "ćie";
        case "ች":
            return "ć";
        case "ቾ":
            return "ćo";
        case "ቿ":
            return "ćwa";
        case "ነ":
            return "ne";
        case "ኑ":
            return "nu";
        case "ኒ":
            return "ni";
        case "ና":
            return "na";
        case "ኔ":
            return "nie";
        case "ን":
            return "n";
        case "ኖ":
            return "no";
        case "ኗ":
            return "nwa";
        case "ኘ":
            return "ńe";
        case "ኙ":
            return "ńu";
        case "ኚ":
            return "ńi";
        case "ኛ":
            return "ńa";
        case "ኜ":
            return "ńie";
        case "ኝ":
            return "ń";
        case "ኞ":
            return "ńo";
        case "ኟ":
            return "ńwa";
        case "አ":
        case "ኣ":
        case "ዐ":
        case "ዓ":
            return "a";
        case "ኡ":
        case "ዑ":
            return "u";
        case "ኢ":
        case "ዒ":
            return "i";
        case "ኤ":
        case "ዔ":
            return "ie";
        case "እ":
        case "ዕ":
            return "";
        case "ኦ":
        case "ዖ":
            return "o";
        case "ከ":
            return "ke";
        case "ኩ":
            return "ku";
        case "ኪ":
            return "ki";
        case "ካ":
            return "ka";
        case "ኬ":
            return "kie";
        case "ክ":
            return "k";
        case "ኮ":
            return "ko";
        case "ኳ":
            return "kwa";
        case "ወ":
            return "we";
        case "ዉ":
            return "wu";
        case "ዊ":
            return "wi";
        case "ዋ":
            return "wa";
        case "ዌ":
            return "wie";
        case "ው":
            return "w";
        case "ዎ":
            return "wo";
        case "ዘ":
            return "ze";
        case "ዙ":
            return "zu";
        case "ዚ":
            return "zi";
        case "ዛ":
            return "za";
        case "ዜ":
            return "zie";
        case "ዝ":
            return "z";
        case "ዞ":
            return "zo";
        case "ዟ":
            return "zwa";
        case "ዠ":
            return "że";
        case "ዡ":
            return "żu";
        case "ዢ":
            return "żie";
        case "ዣ":
            return "ż";
        case "ዤ":
            return "żie";
        case "ዥ":
            return "ż";
        case "ዦ":
            return "żo";
        case "ዧ":
            return "żwa";
        case "የ":
            return "je";
        case "ዩ":
            return "ju";
        case "ዪ":
            return "ji";
        case "ያ":
            return "ja";
        case "ዬ":
            return "jie";
        case "ይ":
            return "j";
        case "ዮ":
            return "jo";
        case "ደ":
            return "de";
        case "ዱ":
            return "du";
        case "ዲ":
            return "di";
        case "ዳ":
            return "da";
        case "ዴ":
            return "die";
        case "ድ":
            return "d";
        case "ዶ":
            return "do";
        case "ዷ":
            return "dwa";
        case "ጀ":
            return "De";
        case "ጁ":
            return "Du";
        case "ጂ":
            return "Di";
        case "ጃ":
            return "Da";
        case "ጄ":
            return "Die";
        case "ጅ":
            return "D";
        case "ጆ":
            return "Do";
        case "ጇ":
            return "Dwa";
        case "ገ":
            return "ge";
        case "ጉ":
            return "gu";
        case "ጊ":
            return "gi";
        case "ጋ":
            return "ga";
        case "ጌ":
            return "gie";
        case "ግ":
            return "g";
        case "ጎ":
            return "go";
        case "ጓ":
            return "gwa";
        case "ጠ":
            return "Te";
        case "ጡ":
            return "Tu";
        case "ጢ":
            return "Ti";
        case "ጣ":
            return "Ta";
        case "ጤ":
            return "Tie";
        case "ጥ":
            return "T";
        case "ጦ":
            return "To";
        case "ጧ":
            return "Twa";
        case "ጨ":
            return "Će";
        case "ጩ":
            return "Ću";
        case "ጪ":
            return "Ći";
        case "ጫ":
            return "Ća";
        case "ጬ":
            return "Ćie";
        case "ጭ":
            return "Ć";
        case "ጮ":
            return "Ćo";
        case "ጯ":
            return "Ćwa";
        case "ጰ":
            return "Pe";
        case "ጱ":
            return "Pu";
        case "ጲ":
            return "Pi";
        case "ጳ":
            return "Pa";
        case "ጴ":
            return "Pie";
        case "ጵ":
            return "P";
        case "ጶ":
            return "Po";
        case "ጷ":
            return "Pwa";
        case "ጸ":
        case "ፀ":
            return "Ce";
        case "ጹ":
        case "ፁ":
            return "Cu";
        case "ጺ":
        case "ፂ":
            return "Ci";
        case "ጻ":
        case "ፃ":
            return "Ca";
        case "ጼ":
        case "ፄ":
            return "Cie";
        case "ጽ":
        case "ፅ":
            return "C";
        case "ጾ":
        case "ፆ":
            return "Co";
        case "ጿ":
            return "Cwa";
        case "ፈ":
            return "fe";
        case "ፉ":
            return "fu";
        case "ፊ":
            return "fi";
        case "ፋ":
            return "fa";
        case "ፌ":
            return "fie";
        case "ፍ":
            return "f";
        case "ፎ":
            return "fo";
        case "ፏ":
            return "fwa";
        case "ፐ":
            return "pe";
        case "ፑ":
            return "pu";
        case "ፒ":
            return "pi";
        case "ፓ":
            return "pa";
        case "ፔ":
            return "pie";
        case "ፕ":
            return "p";
        case "ፖ":
            return "po";
        case "ፗ":
            return "pwa";
        default:
            return "";
    }
};
